/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_hollowcube_luau_util_JNIRefTest */

#ifndef _Included_net_hollowcube_luau_util_JNIRefTest
#define _Included_net_hollowcube_luau_util_JNIRefTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_hollowcube_luau_util_JNIRefTest
 * Method:    newref
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_net_hollowcube_luau_util_JNIRefTest_newref
  (JNIEnv *, jclass, jobject);

/*
 * Class:     net_hollowcube_luau_util_JNIRefTest
 * Method:    unref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_hollowcube_luau_util_JNIRefTest_unref
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_hollowcube_luau_util_JNIRefTest
 * Method:    get
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_net_hollowcube_luau_util_JNIRefTest_get
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
