/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_hollowcube_luau_util_GlobalRef */

#ifndef _Included_net_hollowcube_luau_util_GlobalRef
#define _Included_net_hollowcube_luau_util_GlobalRef
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_hollowcube_luau_util_GlobalRef
 * Method:    newref
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_net_hollowcube_luau_util_GlobalRef_newref
  (JNIEnv *, jclass, jobject);

/*
 * Class:     net_hollowcube_luau_util_GlobalRef
 * Method:    unref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_hollowcube_luau_util_GlobalRef_unref
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_hollowcube_luau_util_GlobalRef
 * Method:    get
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_net_hollowcube_luau_util_GlobalRef_get
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_hollowcube_luau_util_GlobalRef
 * Method:    newweakref
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_net_hollowcube_luau_util_GlobalRef_newweakref
  (JNIEnv *, jclass, jobject);

/*
 * Class:     net_hollowcube_luau_util_GlobalRef
 * Method:    getweak
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_net_hollowcube_luau_util_GlobalRef_getweak
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
