name: Build & Publish to Maven Central

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-core:
    runs-on: ubuntu-latest
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 25 (for JNI)
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'graalvm'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Download jextract
        run: |
          mkdir -p $HOME/.local/jextract
          curl -L https://download.java.net/java/early_access/jextract/22/6/openjdk-22-jextract+6-47_linux-x64_bin.tar.gz | tar -xz -C $HOME/.local/jextract --strip-components=1
          echo "$HOME/.local/jextract/bin" >> $GITHUB_PATH
      - name: Verify jextract is in PATH
        run: which jextract
      - name: Build & Publish
        env:
          TAG_VERSION: ${{ github.ref_name }}
          LUAU_PUBLISH_ROOT: true
        run: ./gradlew nmcpPublishAggregationToCentralPortal
      - name: artifact
        uses: actions/upload-artifact@v4
        with:
          name: luau-${{ github.ref_name }}.jar
          path: native/build/libs/luau-${{ github.ref_name }}.jar
